name: eli_ble_gatt_server
description: "Flutter plugin to turn a device into a BLE GATT Server peripheral (Android & iOS). Supports advertising, custom UUIDs, READ/WRITE/NOTIFY, and real-time event streaming."
version: 0.1.0
homepage: https://github.com/jesus2419/eli_ble_gatt_server
repository: https://github.com/jesus2419/eli_ble_gatt_server
issue_tracker: https://github.com/jesus2419/eli_ble_gatt_server/issues

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.github.jesus2419.eli_ble_gatt_server
        pluginClass: EliBleGattServerPlugin
      ios:
        pluginClass: EliBleGattServerPlugin
